[build]
  publish = "."
  command = "echo 'No build command needed for static site'"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# Configuración para SPA (Single Page Application)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Redirecciones para páginas principales
[[redirects]]
  from = "/home"
  to = "/index.html"
  status = 301

[[redirects]]
  from = "/feed"
  to = "/index.html"
  status = 301

[[redirects]]
  from = "/services"
  to = "/linkedin-servicios.html"
  status = 301

[[redirects]]
  from = "/products"
  to = "/linkedin-productos.html"
  status = 301

[[redirects]]
  from = "/profile"
  to = "/perfil-moderno.html"
  status = 301

# Headers para seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdnjs.cloudflare.com https://fonts.googleapis.com; style-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com https://cdnjs.cloudflare.com; img-src 'self' data: https: blob:; media-src 'self' data: https: blob:; connect-src 'self' https:;"

# Headers para archivos estáticos
[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/imagenes/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Headers para HTML
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# Configuración de formularios
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = false
  minify = true

[build.processing.html]
  pretty_urls = true

# Configuración de funciones (si las necesitas en el futuro)
[functions]
  directory = "netlify/functions"

# Variables de entorno para producción
[context.production.environment]
  NODE_ENV = "production"
  SITE_URL = "https://servilocal.netlify.app"

[context.deploy-preview.environment]
  NODE_ENV = "development"

[context.branch-deploy.environment]
  NODE_ENV = "development"
